services:
  project:
    container_name: animedatabase
    build:
      context: .
      dockerfile: ./dockerfile
    volumes:
      - type: volume
        source: anime_data
        target: /automated/save

volumes:
  anime_data:
