#
# BUILD STAGE
#
FROM maven:3.6.0-jdk-17-slim AS build  
COPY src /usr/src/app/src  
COPY pom.xml /usr/src/app  
COPY checkstyle.xml /usr/src/app
RUN mvn -f /usr/src/app/pom.xml clean package 
#
# PACKAGE STAGE
#
FROM eclipse-temurin:17-jre 
COPY target/automated-1.0-SNAPSHOT.jar /automated/target/automated-1.0-SNAPSHOT.jar  
VOLUME /save
CMD ["java","-jar","/automated/target/automated-1.0-SNAPSHOT.jar"]
